### ISSUE TITLE
Change the English font at headings

### ISSUE THREAD

**Issue by BruceZP** [lotabout/very-simple#10]
One thing that bothers me is that the English font at headings are not so well displayed (unclear). Would there be a way to change it? Thank you.

**Comment by BruceZP** [comment]
![image](https://cloud.githubusercontent.com/assets/16569281/17836905/9232be02-67d5-11e6-916c-627a2b56d837.png)
This is what I mean. I have no idea how to change the .scss file in the theme.
Does this is the **Impact** font you use? 
I need to change the code in _variables.scss file or the very-simple.scss file?

Thank you so much for your kind help.

**Comment by lotabout** [comment]
@BruceZP Sorry for the late reply.
1. You could modify the `$font-header:` in `_variables.scss`, adding/changing to the font you want to use.
2. In my browsers, the font is correctly displayed. May I ask which OS and browser do you use?

**Comment by BruceZP** [comment]
I use win7 with Chrome (Version 52.0.2743.116 m).
