### ISSUE TITLE
怎么添加返回top按钮

### ISSUE THREAD

**Issue by jzbbobo** [lotabout/very-simple#11]
你好，这个主题很赞啊。请问下怎么添加返回top的按钮，谢谢。

**Comment by lotabout** [comment]
@a1311543690 主题目前是不支持“返回TOP“的按钮的，请问你是想知道如何修改主题添加这个功能吗？

**Comment by jzbbobo** [comment]
@lotabout 是的哦，博客太长有这样一个功能便捷些。

**Comment by BruceZP** [comment]
这个功能还是挺有必要的，好像在别人的博文中见过如何给NexT主题添加此功能。

**Comment by lotabout** [comment]
@jzbbobo 要实现这个功能本身是不难的，很粗略地说说怎么做：
1. 需要在 `layout/base.jade` 中添加相应的 HTML 元素，可以是一个 div ，也可以是其它的内容。
2. 为这个元素添加相应的样式 `source/css/very-simple.scss`.
3. 添加点击事件，由于主题本身几乎没有用到 Javascript 交互，所以没有包含外部的 Js 文件，可以考虑直接写到 `layout/base.jade` 文件中。另，参考 [Scroll to the top of the page using JavaScript/jQuery?](http://stackoverflow.com/questions/1144805/scroll-to-the-top-of-the-page-using-javascript-jquery)

我个人认为这个功能是“有更好，没有也行”的类型，本着简单的原则，对于一个博客来说并不是特别重要。

**Comment by jzbbobo** [comment]
好的，非常感谢。
