### ISSUE TITLE
To use author instead of website title in the copyright footnote

### ISSUE THREAD

**Issue by Marlin-Na** [lotabout/very-simple#14]
First appreciate your work on this. 

I noticed that the copyright mark **© 2016 dadada** in the foot used the website title rather than the author in `__config.yml`.

Is there any way or option to change this behavior?

Thanks,

**Comment by Marlin-Na** [comment]
I created a [pull request](https://github.com/lotabout/very-simple/pull/15).

**Comment by lotabout** [comment]
I agree with you, it is better. I've merged your PR.
