### ISSUE TITLE
window下替换very-simple主题打开后空白

### ISSUE THREAD

**Issue by iamchaoge** [lotabout/very-simple#2]
您好，这个主题很赞，不好意思想请问下window下
![1sh mkw 6 9z_ o992jd i](https://cloud.githubusercontent.com/assets/10483361/13075906/8f539820-d4e9-11e5-812c-e46ff46549e6.png)
![s m4 e d2 mn _t wu2i3](https://cloud.githubusercontent.com/assets/10483361/13075911/92fa2fca-d4e9-11e5-9c54-8165e3554cac.png)
![cvl7p5ifc dy8ehop66iclq](https://cloud.githubusercontent.com/assets/10483361/13075913/98009a0e-d4e9-11e5-8511-7819fa6fb453.png)
请问是否第二三条安装命令和window系统有关导致安装主题失败呢？谢谢

**Comment by lotabout** [comment]
@iamchaoge 主题要正确使用，是需要安装依赖的，即你说的第2,3条命令。

从你的截图上看，你并没有执行第2,3条命令，请执行，如果依旧不行，麻烦再发个具体的截图。

谢谢

**Comment by iamchaoge** [comment]
![qq 20160217021839](https://cloud.githubusercontent.com/assets/10483361/13086149/d60ef830-d51c-11e5-8937-6012789a9c64.png)
![2](https://cloud.githubusercontent.com/assets/10483361/13086155/dbfcb138-d51c-11e5-8a49-1751f7574512.png)
T_T  是因为lobash版本低了吗。。

**Comment by lotabout** [comment]
@iamchaoge 这一圈看下来，应该还是版本太低，猜测可能有两个情况：
1. 你的npm版本较低，依据是第一句提示 (npmconf@2.1.2, ....)
2. 你的 hexo 是老的版本，lodash 理论上是安装 hexo 的时候就要安装好的（它是 hexo 的依赖）

能贴个输出吗？执行命令：`hexo --version`

**Comment by iamchaoge** [comment]
我全清空之后重装window下成功了，mac下暂时还未成功...慢慢摸索吧，谢谢啦 :smile:

**Comment by iamchaoge** [comment]
![xxxx](https://cloud.githubusercontent.com/assets/10483361/13099020/24493ac8-d569-11e5-835d-6028f18f5e57.png)
