### ISSUE TITLE
手机预览不能显示列表的前边的小圆点或者数字

### ISSUE THREAD

**Issue by ixinrun** [lotabout/very-simple#23]
手机预览不能显示列表的前边的小圆点或者数字，iphone7，very-simple\source\css\very-simple.scss翻了几遍这里面不知道在哪设置。

**Comment by lotabout** [comment]
@SherwinLuo 做了 responsive，手机屏幕太小，不太适合显示这个样式，就隐藏了。

**Comment by ixinrun** [comment]
@lotabout 嗯，我调了一下列表的缩进以及间距，现在手机上可以显示出来了。还有小小的问题：文章比较长时，pc上快速滑动，最上边黑色头部会有一条白线，点击其他按钮就消失了，用的是火狐，你的demo有时也会出现。

**Comment by lotabout** [comment]
@SherwinLuo 在 FF 下确认有这个问题（但有时候不能重现），Chrome 下没有这个问题。
初步测试是因为 `nav` 元素用了 `position: sticky` 导致的。应该是 FF 的“小 bug“吧，暂时想不到什么解决方案。
