### ISSUE TITLE
你好，我使用你的主题，出现了一些小问题

### ISSUE THREAD

**Issue by xjGafi** [lotabout/very-simple#24]
页面显示以下代码
extends base - var current_title = page.title || tag.name || category.name || site.title block title title= (config.title ? (config.subtitle ? config.title + " | " + config.subtitle : config.title) : "") block main article #index-main.container.entries for post in page.posts.toArray() .post-entry .post-time= post.date.format(config.date_format) .post-desc .post-title if post.link a(href=url_for(post.link),target="_blank", itemprop="url")= post.title else a(href=url_for(post.path))= post.title .post-content if post.description != post.description else if post.excerpt != post.excerpt else if post.content - var br = post.content.indexOf('
') if br < 0 != post.content else != post.content.substring(0, br + 4) .post-meta if (post.tags && post.tags.length) .post-tags != list_tags(post.tags, {show_count: false, class: 'post-tag', style:'none', separator:'/'}) if (post.categories && post.categories.length) .post-categories != list_categories(post.categories, {show_count: false, class: 'post-category', style: 'none', separator: '>'}) include _partial/paginator.jade
试过好多主题后, 我很喜欢这个主题, 但是在最后出现了这个问题.
除了设置我的博客跟目录下的_config.yml文件还需要改动其他地方吗?

**Comment by lotabout** [comment]
@xjGafi 请问你安装了对应的依赖了吗？

```
npm install hexo-renderer-sass --save
npm install hexo-renderer-jade --save
```

**Comment by xjGafi** [comment]
@lotabout
我安装依赖之后解决了这个问题，但页面仅仅只显示纯文字。
在手机和电脑上都是显示纯文字，我访问其他的网页都是正常显示。

**Comment by lotabout** [comment]
@xjGafi 
1. 安装完依赖后尝试 `hexo clean && hexo g` 重新生成页面
2. 如果还是有问题的话麻烦发个截图，“显示纯文字”不太清楚具体是什么情况。

**Comment by xjGafi** [comment]
@lotabout 
    找你说的重新又折腾了一边，还是如图的效果。   
    ![haya good times - google chrome](https://user-images.githubusercontent.com/35452059/37550328-55151132-29c6-11e8-899b-eb92b934d237.jpg)

**Comment by lotabout** [comment]
@xjGafi 看图像是所有的 CSS 都没有正常加载。如果 `sass` 也正常安装了，目前看不出来原因在哪。

你可以尝试一下下面这些命令。这个 repo 有一个分支是 `source`，用来生成主题的 demo 页面。你可以在本地尝试生成，看一下会不会也只有纯文字。

```sh
git clone https://github.com/lotabout/very-simple
git checkout -b source origin/source
git submodule init
git submodule update
npm install
hexo generate
hexo serve
```

**Comment by xjGafi** [comment]
@lotabout 老铁, 我又失败了, 还是老样子, 这两天我的网络(校园网)不稳定, 我过几天在试一试
感谢老铁这几天的指导
谢谢你 : )
