### ISSUE TITLE
页面最上方的"Hexo"如何换成自己的名字？

### ISSUE THREAD

**Issue by qizhengyang2017** [lotabout/very-simple#25]
我是第一次用Hexo，用了你的主题，但我不知道如何将菜单栏上方的“Hexo”换成对自己有意义的文字

**Comment by qizhengyang2017** [comment]
已解决，在根目录下的_config.yml里设置。需要hexo s，才能刷新出来。

**Comment by lotabout** [comment]
关闭 issue，谢谢使用～
