### ISSUE TITLE
searching capabilitie

### ISSUE THREAD

**Issue by ChenTaoSpace** [lotabout/very-simple#26]
how to add it

**Comment by lotabout** [comment]
The theme is trying to be as minimal as possible. Currently there is not built in support. I myself don't use this theme any more. Thus won't add any new features.

If you are interest in tinkering around, you could try:
- Add plugin [hexo-generator-search](https://github.com/wzpan/hexo-generator-search) to your blog and try to add search box to this theme
- Try some 3rd party search engine like [switftype](https://swiftype.com/) or [Algolia](https://www.algolia.com/)
