### ISSUE TITLE
很喜欢你的主题，多说那个能不能搞个评论框啊？

### ISSUE THREAD

**Issue by iT2afL0rd** [lotabout/very-simple#3]
现在的分享感觉不实用啊，关键jade语法太复杂，搞不明白。
Thanks

**Comment by lotabout** [comment]
@iT2afL0rd Hi, 我更新了一下主题，你可以再看看。下面是预览

![selection_039](https://cloud.githubusercontent.com/assets/1527040/13656608/480d5840-e6a3-11e5-874d-709c83e3bb1d.png)

**Comment by iT2afL0rd** [comment]
Hi, 试了一下，可以用，Thanks。
