### ISSUE TITLE
How to Modify the publish time of a post?

### ISSUE THREAD

**Issue by timqi** [lotabout/very-simple#4]
It's cool this Theme!

when I migrate from jekyll, I paste my *.md file to source/_post folder. but publish time of posts become all the same when i do the paste. how to handle this?

**Comment by lotabout** [comment]
@timqi The time is defined on the top of your post, like this(the `date` field):

```
title: <The title of your post>
date: 2016-02-06 09:37:13
tags: [C, compiler]
categories: Project
toc:
---
<The actual content>
```

This format is defined by hexo.

**Comment by timqi** [comment]
thx!
