### ISSUE TITLE
Windows执行npm install hexo-renderer-sass --save问题

### ISSUE THREAD

**Issue by Shineee** [lotabout/very-simple#8]
#2

这个issues的解决方案依旧是下面的效果：

![qq 20160715142848](https://cloud.githubusercontent.com/assets/2569939/16865901/b9874cd2-4a9a-11e6-97ae-f9629c4d1496.png)

执行npm install hexo-renderer-jade --save正确
执行npm install hexo-renderer-sass --save过程报错。
下面是报错的信息：
![qq 20160715144816](https://cloud.githubusercontent.com/assets/2569939/16866023/d49d584e-4a9b-11e6-9187-9eaf69e51061.png)
![qq 20160715145024](https://cloud.githubusercontent.com/assets/2569939/16866022/d46cd0e8-4a9b-11e6-945d-5fa27e1b0706.png)
我的工具版本：
![qq 20160715145345](https://cloud.githubusercontent.com/assets/2569939/16866048/fee10b5a-4a9b-11e6-8c18-2f256079aa0f.png)
NPM version: 3.10.5
帮看下呗

**Comment by lotabout** [comment]
@Shineee 根据提示错误，应该是 `hexo-renderer-sass` 安装后是需要编译的，而你的环境里似乎缺少 `vcbuild` 啊。

话说安装了 Visual Studio 2005 了吗？你就先按着提示的错误信息安装相关的依赖试试吧。

**Comment by Shineee** [comment]
额。好麻烦。。安装2005简直是噩梦，我还是换个主题吧，谢谢你的回答
