### ISSUE TITLE
How to configure templated about page 

### ISSUE THREAD

**Issue by BruceZP** [lotabout/very-simple#9]
I got a question about how to configure the new 'about' page with the template of normal article. I have tried following the instruction in the readme.md file. However, I could only got a blank page when click about page. Do I need to write html file for what I need. Thank you.

**Comment by lotabout** [comment]
You could include `layout: post` in your `about/index.md` So that it looks like:

```
title: About
layout: post
---
```

The options are base, page, post which are defined in `layout/` of the theme.

**Comment by BruceZP** [comment]
By doing this, it turn out to be like the image shows:
![image](https://cloud.githubusercontent.com/assets/16569281/17814669/7971714c-6663-11e6-8b30-2b3212922044.png)

**Comment by lotabout** [comment]
This is quite strange, would you please share the source code of your blog?

I tested mine and it works well. Both creating a new page or change the `layout` of that page will work.

**Comment by BruceZP** [comment]
Please have a check of this: https://github.com/BruceZP/BruceZP.github.io 
Thank you.

**Comment by lotabout** [comment]
Hi, your repository does not contain the source code. The `master` branch is the generated (deployed) html. Without the source code, it is hard to find out what's happening.

BTW, you can checkout mine: https://github.com/lotabout/lotabout.github.io/tree/source. I have an `about` page in my blog.

**Comment by BruceZP** [comment]
The problem was solved by reading your codes.
I got it wrong by reading this:
![image](https://cloud.githubusercontent.com/assets/16569281/17828802/7390c2b2-66ce-11e6-98b7-a1f24320772c.png)
I thought the source folder is the one under very-simple folder.
Thank you so much for your kind help.
